PAPERNAME=fig
TEXFILES =  *.tex *.bib *.sty

all:
	latex -shell-escape fig.tex

clean:
	rm -f *.ps $(PAPERNAME).pdf *.dvi *.txt *.aux *.log *.blg *.bbl *~ *.ilg *.idx *.out *.in *.dpth *.md5 *.eps *.pdf *.auxlock
